/*
 * @Author: Diskfan
 * @Date: 2019-05-15 09:38:43 
 * @Last Modified by: Diskfan
 * @Last Modified time: 2019-06-18 11:22:52
 */
export default {
    examine: [{
        label: '时间',
        prop: 'createTime',
        minWidth: '180px',
        type: 'time',
        format: 'YYYY-M-D HH:mm:ss',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '账号',
        prop: 'account',
        minWidth: '100px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '币种',
        prop: 'coinName',
        minWidth: '90px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '数量',
        prop: 'amount',
        minWidth: '90px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '手续费',
        prop: 'fee',
        minWidth: '110px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '状态',
        prop: 'recdStatus',
        minWidth: '90px',
        overflowTip: true,
        selectHeader: true,
        type: 'config|recdStatus'
    }, {
        label: 'From地址',
        prop: 'fromAddr',
        minWidth: '130px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: 'To地址',
        prop: 'toAddr',
        minWidth: '120px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '订单号',
        prop: 'orderId',
        minWidth: '150px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: 'TXID',
        prop: 'txId',
        minWidth: '100px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '备注',
        prop: 'userRemark',
        minWidth: '90px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '上链备注',
        prop: 'sysRemark',
        minWidth: '120px',
        overflowTip: true,
        selectHeader: true
    }],
    monitoring: [{
        label: '时间',
        prop: 'createTime',
        type: 'time',
        format: 'YYYY-M-D HH:mm:ss',
        minWidth: '150px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '转账类型',
        prop: 'transTypeStr',
        minWidth: '150px',
        selectHeader: true
    }, {
        label: '币种',
        prop: 'coinName',
        minWidth: '100px',
        selectHeader: true
    }, {
        label: '来源地址',
        prop: 'fromAddr',
        minWidth: '200px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '目标地址',
        prop: 'toAddr',
        minWidth: '200px',
        selectHeader: true
    }, {
        label: '到账数量',
        prop: 'blockAmount',
        minWidth: '120px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '手续费',
        prop: 'blockFee',
        minWidth: '110px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: 'TXID',
        prop: 'txId',
        minWidth: '100px',
        overflowTip: true,
        selectHeader: true
    }, {
        label: '操作人',
        prop: 'sysUserId',
        overflowTip: true,
        minWidth: '110px',
        selectHeader: true
    }],
    platformAccount: [{
        label: '序号',
        prop: 'index'
    }, {
        label: '账号',
        prop: 'account'
    }, {
        label: '昵称',
        prop: 'address'
    }, {
        label: 'USTD',
        prop: 'ustd'
    }, {
        label: '注册时间',
        prop: 'regist'
    }],
    userAccount: [{
        label: '排名',
        prop: 'rank'
    }, {
        label: '账号',
        prop: 'account'
    }, {
        label: '昵称',
        prop: 'address'
    }, {
        label: 'USTD',
        prop: 'ustd'
    }, {
        label: '注册时间',
        prop: 'regist'
    }]
}